apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-odf-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: my-odf
    server: https://kubernetes.default.svc
  project: default
  source:
    path: application-mainfest
    repoURL: https://github.com/mfau007/my-odf
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
