{{- if not $.Values.mcgstandalone.enabled }}
{{- if $.Values.cephtools.enabled }}
---
apiVersion: ocs.openshift.io/v1
kind: OCSInitialization
metadata:
  name: ocsinit
  namespace: openshift-storage
  annotations:
spec:
  enableCephTools: true
{{- end }}
{{- end }}
