apiVersion: v1
data:
  CSI_PLUGIN_TOLERATIONS: |
    - key: node-role.kubernetes.io/infra
      operator: Equal
      value: ""
      effect: NoSchedule
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
