apiVersion: v1
data:
  CSI_PLUGIN_TOLERATIONS: |
    - key: nodetype	    - key: node-role.kubernetes.io/infra
      operator: Equal	      operator: Equal
      value: infra	      value: ""
      effect: NoSchedule	      effect: NoSchedule
    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
